### ISSUE TITLE
SdpOrigin contains redundant representation of IP address type

### ISSUE THREAD

**Issue by Paul-E** [nils-ohlmeier/rsdparsa#14]
[SdpOrigin](https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/lib.rs#L42) has [SdpAddrType](https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/network.rs#L13) which is an enum that tells us if the address is IPv4 or IPv6, but SdpOrigin also has an [IpAddr](https://doc.rust-lang.org/std/net/enum.IpAddr.html) which contains this information as well. This information should be de-duplicated.

**Comment by nils-ohlmeier** [comment]
While changing that the IP address parsing should probably be changed to use IpAddr::from_str() no matter what the SdpAddrType suggested. That should simplify the code quite a bit.

**Comment by Paul-E** [comment]
`IpAddr::from_str` potentially returns its own error. Should we introduce a `cause: Option<Box<Error>>` field [here](https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/error.rs#L7) so cause can return this underlying error? We can open a separate issue for this if so.

**Comment by nils-ohlmeier** [comment]
My understanding is that boxed errors are nice because they all look the same, but you can not distinguish them.
I think what needs to happen instead is to add an error here: https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/error.rs#L13
With the error which IpAddr::from_str() can return. And then add a the matching From here https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/error.rs#L62

**Comment by Paul-E** [comment]
Good point, I agree it should be done that way. Should this be in the pull request for this issue, or a separate one.
