### ISSUE TITLE
Consolidate direction attribute

### ISSUE THREAD

**Issue by Paul-E** [nils-ohlmeier/rsdparsa#76]
We have [`SdpAttributeDirection`](https://github.com/nils-ohlmeier/rsdparsa/blob/c74eb8df4bb134cb96fa6c81b2b71aea6491ef0e/src/attribute_type.rs#L193) with `Recvonly`, `Sendonly`, and `Sendrecv`. We also have [`SdpAttribute`](https://github.com/nils-ohlmeier/rsdparsa/blob/c74eb8df4bb134cb96fa6c81b2b71aea6491ef0e/src/attribute_type.rs#L318) whicih has `Recvonly`, `Sendonly`, and `Sendrecv`. If these are the same, we should consolidate them.

**Comment by nils-ohlmeier** [comment]
The SdpAttributeDirection is only used for 'extmap' which explicitly does not support the 'Inactive' value (because it makes no sense).
But the SdpAttribute actually contains 'Inactive', 'Recvonly', 'Sendonly' and 'Sendrecv'. So no they are not the same.
And I don't see an easy way to define one as the super set of another. So I suggest don't try to consolidate these.
